// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// PLACEHOLDER: estimated windows only (no ElevenLabs voice yet). gen_voice.py overwrites this
// file with REAL per-word times; the composition's cues are derived from these words, so
// everything re-syncs on its own.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'This handshake is a contract. No paper needed.', start: 0.4, end: 3.3 },
  { text: 'Most people think if it\'s not in writing, it\'s not a contract.', start: 4.0, end: 8.4 },
  { text: 'You sell your bike for fifty thousand. Just a handshake.', start: 9.0, end: 12.6 },
  { text: 'Pause. Can the buyer walk away?', start: 13.2, end: 15.6 },
  { text: 'Under Section ten of the Indian Contract Act, writing isn\'t required.', start: 17.4, end: 21.5 },
  { text: 'Free consent. Competent parties. Lawful consideration. Lawful object.', start: 22.2, end: 26.0 },
  { text: 'Tick those boxes, and a spoken deal binds both sides.', start: 26.6, end: 30.2 },
  { text: 'The exception? Selling land needs a registered deed.', start: 30.9, end: 33.9 },
  { text: 'But valid isn\'t provable. One WhatsApp confirming the deal — that\'s your paper.', start: 34.5, end: 39.0 },
];
